server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: pictureService
  datasource:
    url: jdbc:postgresql://localhost:5432/cookstarter
    username: postgres
    password: 13root13
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    enabled: false

app:
  name-length: 13
  jwt:
    secret-key: topsecretkey123rieubherotuh3498th398gh395g8h598gh4g8gidufghdifughi43gg4334t3h4gi34uhgi35uhgi35ughi45ugho98dhf98bhg